
spring.application.name: api
spring.profiles.active: local

spring:
  config:
    import:
      - db.yml
      - jwt.yml
      - openai.yml
      - fcm.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080

---
spring.config.activate.on-profile: local



---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
