spring:
  config:
    activate:
      on-profile: test

openai:
  model: test
  api:
    url: test-url
    key: test-key

---
spring:
  config:
    activate:
      on-profile: local

openai:
  model: local
  api:
    url: local-url
    key: local-key
