spring:
  config:
    activate:
      on-profile: test

openai:
  model: ${OPENAI_API_MODEL}
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local

openai:
  model: ${OPENAI_API_MODEL}
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}

---
spring:
  config:
    activate:
      on-profile: live

openai:
  model: ${OPENAI_API_MODEL}
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}
