spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100
---
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_schema: chewing
  h2:
    console:
      enabled: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.1.0

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:CHEWING;MODE=MySQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS CHEWING;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---

spring.config.activate.on-profile: local
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  data:
    mongodb:
      host: localhost
      port: 27018
      database: chewing
      authentication-database: admin
      username: root
      password: root

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/chewing?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---


spring.config.activate.on-profile: live

## 실제시 삭제
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  ## 실제시 삭제 =========================
  data:
    mongodb:
      host: ${STORAGE_DATABASE_MONGO_DB_HOST}
      port: ${STORAGE_DATABASE_MONGO_DB_PORT}
      database: ${STORAGE_DATABASE_MONGO_DB_NAME}
      authentication-database: admin
      username: ${STORAGE_DATABASE_MONGO_DB_NAME}
      password: ${STORAGE_DATABASE_MONGO_DB_PASSWORD}

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${STORAGE_DATABASE_CORE_DB_HOST}:${STORAGE_DATABASE_CORE_DB_PORT}/${STORAGE_DATABASE_CORE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
      username: ${STORAGE_DATABASE_CORE_DB_USERNAME}
      password: ${STORAGE_DATABASE_CORE_DB_PASSWORD}
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
